Solving classpath problems and warnings

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,9 +1,23 @@
 #!/bin/zsh
+
+export MVN_ANDROID_BUILD_TOOL_VERSION=22.0.1
+export MVN_JAVA_VERSION=1.5
+
+
+export JAVA_HOME="/usr/lib/jvm/jdk1.8"
+export JAVA_JAR="/usr/lib/jvm/jdk$MVN_JAVA_VERSION/bin/jar"
+export ANDROID_HOME="$HOME/android-sdk/"
+export PATH=$PATH:$ANDROID_HOME/build-tools/$MVN_ANDROID_BUILD_TOOL_VERSION:$JAVA_HOME/bin
+
+command -v adb >/dev/null 2>&1 || { echo >&2 "I require adb but it's not installed.  Aborting."; exit 1; }
+command -v $JAVA_JAR >/dev/null 2>&1 || { echo >&2 "I require jar but it's not installed.  Aborting."; exit 1; }
+command -v sh >/dev/null 2>&1 || { echo >&2 "I require sh but it's not installed.  Aborting."; exit 1; }
+command -v aapt >/dev/null 2>&1 || { echo >&2 "I require aapt but it's not installed.  Aborting."; exit 1; }
+
 # adb shell am force-stop br.com.vt.mapek/br.com.vt.mapek.android.StatusActivity
 adb shell rm -rf /data/data/br.com.vt.mapek/cache
 
-export ANDROID_HOME="$HOME/android-sdk/"
-export PATH=$PATH:$ANDROID_HOME/build-tools/19.1.0
+
 
 dxmefunc() {
     dx --dex --core-library --output=classes.dex $1 && aapt add $1 classes.dex
@@ -45,7 +59,7 @@ dxallfunc(){
 	find . -name *.jar -type f \\
 	-exec echo :: Criando JAR :: {} \; \\
 	-exec rm {}  \; \\
-	-exec jar cfm {} META-INF/MANIFEST.MF . \; \\
+	-exec $JAVA_JAR cfm {} META-INF/MANIFEST.MF . \; \\
 	-exec echo :: Injetando dex no JAR \$(pwd)/{} \; \\
 	-exec dx --dex --core-library --output=classes.dex {} \; \\
 	-exec aapt add {} classes.dex  \; \\
@@ -63,7 +77,8 @@ dxallfunc(){
 	
 alias dxme=dxmefunc
 alias dxall=dxallfunc
-
+export dxall=dxallfunc
+export dxme=dxmefunc
 # echo Gerando numeros randomicos && \
 # shuf -i 1-100000000 | tr '\n' ',' > mapek.bundles/mapek.bundles.resource/src/main/resources/input.csv && \
 echo Construindo o Projeto && \
@@ -75,5 +90,4 @@ adb install -r mapek.android/target/mapek.android-1.0-SNAPSHOT.apk && \
 adb shell am start -n br.com.vt.mapek/br.com.vt.mapek.android.StatusActivity && \
 
 #Result
-# watch -n 1 adb pull /storage/sdcard/result.csv
-adb shell rm /storage/sdcard/result.csv && watch adb shell 'cat /storage/sdcard/result.csv'
+watch -n 1 adb pull /storage/sdcard0/result.csv
